config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "articles#index"
  #devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :articles do
    resources :comments do 
      resources :responses
    end
    resources :marks, only: :create
  end

  resources :users, except: :index
  get "/about" => 'application#about', as: "about"

  #post 'comment/:id/response' => "responses#create", as: :comment_responses
  #get 'comment/:id/response' => "responses#new", as: :new_comment_responses

end

app/models/comment.rb
class Comment < ApplicationRecord
  VALUE_RATING = 5
  validates :content, presence: true, length: { minimum: 1 }

  belongs_to :article
  belongs_to :user
  has_many :responses

  after_create :update_counter_inc, :add_rating
  after_destroy :update_counter_dec, :remove_rating

  private
    def update_counter_inc
      self.article.comment_inc 
    end

    def update_counter_dec
      self.article.comment_dec
    end

    [:add, :remove].each do |action|
    class_eval %Q{
      def #{action}_rating 
        self.user.#{action}_rating VALUE_RATING
      end
    }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :set_article, only: [:create, :destroy, :edit, :update]
  load_and_authorize_resource except: :create

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  def create
    #binding.pry
    @comment = Comment.new comment_params
    @comment.user = current_user
    @comment.article_id = params[:article_id]
    authorize! :create, @comment

    if @comment.save
      #redirect_to @article
      respond_to do |format|
        format.js {}
      end
    else
      redirect_to @article, notice: 'Комментарий не сохранён'
    end
  end

  def edit
  end

  def update 
    if @comment.update(comment_params)
      respond_to do |format|
        format.js {}
      end
    end    
  end

  def destroy
    #article = Article.find params[:article_id]
    @comment.destroy
    respond_to do |format|
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_article
      article_params = params.require(:article_id)
      @article = Article.find(article_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.row.comment id="#{comment.id}"
	.body-comment
		.col-md-2.col-sm-3.col-xs-3
			= link_to user_path comment.user do
				- if comment.user.avatar.url.nil?
					= image_tag "Crisis_club_icon_profile.png", style: "border:none"
				- else 
					= image_tag comment.user.avatar.for_message.url
		.col-md-10.col-sm-9.col-xs-9
			.row
				.col-md-3.col-sm-6.col-xs-6
					= link_to user_path comment.user do
						= first_and_last_name comment.user
				.col-md-9.col-sm-6.col-xs-6
					= created_at_article comment
					= image_level comment.user
			.row
				.col-md-12.col-sm-12.col-xs-12.comment-content
					= comment.content
				.col-md-12.col-sm-12.col-xs-12.comment-toolbar
					= link_to "Ответить", new_article_comment_response_path(@article, comment), remote: true if can? :create, Comment
					br.hidden-md.hidden-lg
					= link_to "Удалить", article_comment_path(@article, comment), remote: true, method: :delete, data: { confirm: 'Вы действительно хотите удалить комментарий?' } if can? :destroy, comment 
					br.hidden-md.hidden-lg
					= link_to "Редактировать", edit_article_comment_path(@article, comment), remote: true if can? :update, comment
		.col-md-12.col-sm-12.col-xs-12.responses
			= render comment.responses unless comment.responses.empty?

app/views/comments/_comments.html.slim
.comments-header
	- if @article.comments_count == 0
		b
			|Комментариев нет
	- else
		.exists-comments
			.icon
			b
				|Комментарии(
				= @article.comments_count
				|)
.comments
	- @article.comments.each do |comment|
		= render 'comments/comment', comment: comment

app/views/comments/_form.html.slim
.comment-form.row
	.col-md-2.col-sm-3.col-xs-3
		.avatar
			- if current_user.avatar.url.nil?
				= image_tag "Crisis_club_icon_profile.png", style: "border:none;"
			- else 
				= image_tag current_user.avatar.for_message.url
	.col-md-10.col-sm-9.col-xs-9			
		.content
			.name-user
				= first_and_last_name current_user
			= simple_form_for [@article, @article.comments.new], remote: true, html:{ "data-turbolinks" => false } do |f|
			  = f.input :content, label: false, input_html: { rows: '3'}
			  = f.button :submit, 'Отправить'

app/views/comments/_form_update.html.slim
  .col-md-12.col-sm-12.col-xs-12.form_update     
    .content
      .name-user
        | Редактирование
      = simple_form_for [@article, @comment], remote: true, html:{ "data-turbolinks" => false } do |f|
        = f.input :content, label: false, input_html: { rows: '3'}
        = f.button :submit, 'Отправить'

app/views/comments/_index.html.slim
= render 'comments/comments'
- if current_user
	= render 'comments/form' if can? :create, Comment
- else
	.bs-callout.bs-callout-info.text-left
		| Чтобы оставить комментарий пожалуйста 
		span#go-registration зарегистрируйтесь

app/views/comments/create.js.erb
$(".show-article .comments").append('<%= escape_javascript(render @comment) %>')

app/views/comments/destroy.js.erb
$(".comments #<%= @comment.id %>").remove()

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/edit.js.erb
$(".comments #<%= @comment.id %> .body-comment").fadeOut('fast',function() {
	$(".comments #<%= @comment.id %>").append("<%= escape_javascript(render partial: 'form_update') %>")
})

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
= link_to 'Edit', edit_comment_path(@comment)
'|
= link_to 'Back', comments_path

app/views/comments/update.js.erb
$(".comments #<%= @comment.id %> .comment-content").html("<%= @comment.content.strip %>")
.promise($(".comments #<%= @comment.id %> .body-comment").fadeIn('fast'))
$(".form_update").remove()