config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "articles#index"
  #devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :articles do
    resources :comments do 
      resources :responses
    end
    resources :marks, only: :create
  end

  resources :users, except: :index
  get "/about" => 'application#about', as: "about"

  #post 'comment/:id/response' => "responses#create", as: :comment_responses
  #get 'comment/:id/response' => "responses#new", as: :new_comment_responses

end

app/models/article.rb
class Article < ApplicationRecord
  attr_accessor :tag_list

  VALUE_RATING = 20

  validates :content, presence: true, length: { minimum: 1 }
  validates :title,   presence: true
  validates :illustration, presence: true
  validates :description, presence: true

  scope :published, -> { where(published: true) }
  scope :not_published, -> { where(published: false) }
  default_scope { order(created_at: :desc) }

  paginates_per 9

  belongs_to :user
  has_many :comments
  has_many :marks
  has_and_belongs_to_many :tags

  after_save :add_rating
  after_destroy :remove_rating

  mount_uploader :illustration, IllustrationUploader
  
  def published?
    self.published 
  end

  [:add, :remove].each do |action|
    class_eval %Q{
      def #{action}_rating
        self.user.#{action}_rating VALUE_RATING if self.published?
      end
    }
  end 

  def update_comments_counter
    update_attribute(:comments_count, comments_count)
  end

  def mark_inc
    Article.increment_counter(:marks_count, self.id)
  end

  def mark_dec
    Article.decrement_counter(:marks_count, self.id)
  end

  def comment_inc
    Article.increment_counter(:comments_count, self.id)
  end

  def comment_dec
    Article.decrement_counter(:comments_count, self.id)
  end

  rails_admin do 
    edit do   
      field :title
      field :description
      field :content
      field :illustration
      field :published
      field :tags
      field :user_id, :hidden do
        default_value do
          bindings[:view]._current_user.id
        end
      end
    end 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:create, :update]


  # GET /articles
  # GET /articles.json
  def index
    if params[:tag].nil?
      if params[:my_article]
        #current_user.articles.not_published
        if current_user.articles.not_published.empty?
          @message = "Вы не предложили ни одной новости или их уже опубликовали"
        else
          @articles = current_user.articles.page params[:pages]
        end
      else  
        @articles = Article.published.page params[:page]
      end
    else
      @articles = Tag.find_by(tag: params[:tag]).articles.page params[:pages]
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.published.where.not(id: @article.id).limit(5)
    @liked = (!current_user.nil? && @article.marks.exists?(user_id: current_user.id)) ? "" : "grey" 
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article.tag_list = @article.tags.map { |i| i.tag }.join(" ")
    #binding.pry
   end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    authorize! :create, @article
    respond_to do |format|
      if @article.save
        tag_array = find_or_create_tags(params[:tags].map{|k, v| v}) unless params[:tags].empty? || params[:tags]["0"].empty?
        @article.tags << tag_array.compact unless tag_array.nil?
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize! :make_publication, @article if params[:article][:published] == "1"
    #binding.pry
    respond_to do |format|
      if @article.update(article_params)
        old_tags = @article.tags.map { |i| i.tag }
        new_tags = params[:tags].map { |key, value| value }
        delete_tags(old_tags - new_tags)
        @article.tags << find_or_create_tags(new_tags - old_tags)
        #@article.tags << find_or_create_tags unless params[:tags].empty?
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def find_or_create_tags tags
      tags.map do |value|
        Tag.find_or_create_by(tag: value) unless value.empty?
      end
    end

    def delete_tags tags
      tags.each do |tag|
        Tag.where(tag: tag).destroy_all
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :published, :illustration, :description)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def link_to_tag tag
    link_to "\##{tag.tag}", articles_path(tag: tag.tag)
  end

  def created_at_article article
    article.created_at.strftime("%d.%m.%Y") + " в " + article.created_at.strftime("%R")
  end
end

app/views/articles/_article.html.slim
.article
  .image
    = link_to article do
      = image_tag(article.illustration.thumb.url, class: "img-responsive") unless article.illustration.file.nil?
  .title
    = link_to "#{article.title}", article_path(article)
  .footer-article
    .date
      = article.created_at.strftime("%d.%m.%Y")
    .marks 
      .icon         
      = article.marks_count
    .comments
      .icon 
      = article.comments_count

app/views/articles/_article_sidebar.html.slim
.sidebar
	.articles-sidebar
		h1 style="margin-top:-3px"
			|Следующие новости:
		- @articles.each do |article|
			= render article

app/views/articles/_articles.html.slim
.row	
	- @articles.each_with_index do |article, i|
	    .col-md-4.col-sm-6.col-xs-12.thumb
	        = render article

app/views/articles/_form.html.slim
= tinymce_assets
= simple_form_for @article, html:{ id: "article_form" } do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message
  = f.input :title, label: "Название"
  = f.input :description, label: "Описание"
  = f.input :content, label: "Текст" , input_html: { class: "tinymce" }
  = tinymce plugins: "media code"
  = f.input :tag_list, label: "Список тегов(введите через пробел)"
  = f.input :published, label: "Опубликовать" if cannot? :make_publication, current_user

  .form-group
    = f.file_field :illustration
  .form-group
    = f.submit "Предложить новость", class: "btn btn-primary"

app/views/articles/_shared_buttons.html.erb
<div class="shared-button" data-turbolinks="false">
  <div class="shared-title">
    Поделиться:
  </div>
  <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5878b92b77b16ed8">
  </script>
  <div class="addthis_inline_share_toolbox"></div>

</div>

<div id="vk_share_button"></div>

app/views/articles/edit.html.slim
h1 Редактирование статьи

= render 'form'

= link_to "Назад", current_user

app/views/articles/index.html.slim
- if @message
    h1 
        = @message
- else    
    .articles.clear-fix
        = render partial: "articles"
    .add-articles-index.text-center.row
        = link_to_next_page @articles, "<div id='add-articles-index'>Показать ещё</div>".html_safe, remote: true
        .go-top style="display:none"
            a href="#"


    	

app/views/articles/index.js.erb
$(".articles").append("<%= escape_javascript(render partial: 'articles') %>");
<% unless (link_to_next_page @articles, 'Показать ещё', remote: true).nil? %>
	$(".add-articles-index").html("<%= escape_javascript(link_to_next_page @articles,\
	 	'<div id=\'add-articles-index\'>Показать ещё</div>'.html_safe, remote: true) %> \
		<div class='go-top'><a href='#'></a></div>");
<% else %>
	$(".add-articles-index").html("<div class='go-top'><a href='#'></a></div>")	
<% end %>

app/views/articles/new.html.slim
h1 Добавление статьи

= render 'form'

= link_to "Назад", current_user

app/views/articles/show.html.slim
/p#notice = notice
- meta title: @article.title, og: { image: base_url + @article.illustration.for_shared.url, title: @article.title, description: @article.description,	url: current_url }
.container
	.row
		.col-md-8.col-xs-12.col-sm-12
			.show-article
				h1.hidden-xs.hidden-sm = @article.title
				.created-at.hidden-xs.hidden-sm
					= created_at_article @article
					.shared-top
						= render partial:"shared_buttons"
				= image_tag(@article.illustration.url, class: "img-responsive") unless @article.illustration.file.nil?
				h1.hidden-md.hidden-lg = @article.title
				.content
					= @article.content.html_safe
				.footer-article
					.marks 
						= link_to article_marks_path(@article), method: :post, remote: true do
							.like class=" #{@liked}"
								.icon
								span Мне нравится
					span.count-like 
						= "(#{@article.marks_count})"
					= render partial: "shared_buttons"	
				.tags
					|Теги: 
					- @article.tags.each do |tag|
						= link_to_tag tag		
				= render 'comments/index'
		.col-md-4.col-xs-12.col-sm-12
			= render "article_sidebar"