config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "articles#index"
  #devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :articles do
    resources :comments do 
      resources :responses
    end
    resources :marks, only: :create
  end

  resources :users, except: :index
  get "/about" => 'application#about', as: "about"

  #post 'comment/:id/response' => "responses#create", as: :comment_responses
  #get 'comment/:id/response' => "responses#new", as: :new_comment_responses

end

app/models/user.rb
class User < ApplicationRecord
  before_create :setup_default_role_for_new_users

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  extend Enumerize
  enumerize :role, in: [:user, :moderator, :admin]

  #validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :articles
  has_many :comments
  has_many :marks
  has_many :responses
  
  mount_uploader :avatar, AvatarUploader

  def self.find_for_oauth(auth, signed_in_resource = nil)

    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      #email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email #if email_is_verified
      user = User.where(:email => email).first if email

      if user.nil?        
        if auth.provider == "facebook"
          first_name, last_name = auth.info.name.split(" ")
        elsif auth.provider == "vkontakte"
          first_name = auth.extra.raw_info.first_name 
          last_name = auth.extra.raw_info.last_name
          dob = auth.extra.raw_info.bdate  
        end
        user = User.new(
          first_name: first_name,
          last_name: last_name,
          dob: dob,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        #user.skip_confirmation!
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def title
    self.email
  end

  def add_rating val
    self.rating += val
    self.save
  end

  def remove_rating val
    self.rating -= val
    self.save
  end

  def get_level
    case self.rating
      when 0 .. 50 then 0
      when 51 .. 200 then 1
      when 201 .. 500 then 2
      when 501 .. 1000 then 3
      when 1001 .. 3000 then 4
      else
        5 
    end    
  end

  rails_admin do
    edit do
      field :email 
      field :first_name do
        label "Имя"
      end
      field :last_name do 
        label "Фамилия"
      end
      field :role do 
        label "Роль"
      end
      field :rating do
        label "Рейтинг"
      end

    end
  end



  private

    def setup_default_role_for_new_users
      if self.role.blank?
        self.role = "user"
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :finish_signup]
  before_action :authenticate_user!, :except => :show
  load_and_authorize_resource
  # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all
  # end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format| 
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        #@user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :phone, :avatar, :company, :position, :business_achievements, :dob)
    end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def first_and_last_name user
    user.first_name + " " + user.last_name
  end

  def image_level user
    image_tag "level_#{user.get_level}.png", class: "rating-image"
  end

end

app/views/users/_form.html.slim
= form_for(@user, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @user.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@user.errors.count,"error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :first_name, class: "col-sm-2 control-label" do
      | Имя
    .col-sm-10
      = f.text_field :first_name, class: "form-control"
  .form-group
    = f.label :last_name, class: "col-sm-2 control-label" do
      | Фамилия
    .col-sm-10
      = f.text_field :last_name, class: "form-control"
  .form-group
    = f.label :phone, class: "col-sm-2 control-label" do
      | Телефон
    .col-sm-10
      = f.text_field :phone, class: "form-control"
  .form-group
    = f.label :company, class: "col-sm-2 control-label" do
      | Компания
    .col-sm-10
      = f.text_field :company, class: "form-control"
  .form-group
    = f.label :position, class: "col-sm-2 control-label" do
      | Должность
    .col-sm-10
      = f.text_field :position, class: "form-control"
  .form-group
    = f.label :business_achievements, class: "col-sm-2 control-label" do 
      | Бизнес достижения
    .col-sm-10
      = f.text_area :business_achievements, class: "form-control"
  .form-group
    .col-sm-2.control-label
      |Avatar
    .col-sm-10
      = f.file_field :avatar
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit "Cохранить", class: "btn btn-primary"

app/views/users/edit.html.slim
.page-header
  h1
    | Редактирование 
    | пользователя

= render 'form'

app/views/users/finish_signup.html.slim
div id="add-email" class="container"
  h1 Дoбавьте email
  = form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f|
    - if @show_errors && current_user.errors.any?
      div id="error_explanation">
        - current_user.errors.full_messages.each do |msg|
          = msg 
          br
    div class="form-group"
      = f.label :email
      div class="controls"
        = f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Например: email@me.com'
        p class="help-block"
          |Пожалуйста, подтвердите свой email.
    div class="actions"
      = f.submit 'Continue', :class => 'btn btn-primary'

app/views/users/new.html.slim
.page-header
  = link_to users_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | user

= render 'form'

app/views/users/show.html.slim
.page-header
  
.row
  .col-md-4
    - if @user.avatar.file.nil?
      = image_tag "Crisis_club_icon_profile.png"
    - else
      = image_tag(@user.avatar.thumb.url, class: "img-responsive")
  .col-md-8
    dl.dl-horizontal
      dt
        | Email:
      dd
        = @user.email
      dt
        | Имя:
      dd
        = @user.first_name
      dt
        | Фамилия:
      dd
        = @user.last_name
      dt
        | Рейтинг
      dd.user-rating
        = @user.rating
        = image_level @user
      dt
        | Телефон:
      dd
        = @user.phone == "" ? "не указан" : @user.phone
      dt
        | Место работы
      dd
        = @user.company == "" ? "не указано" :  @user.company
      dt
        | Должность
      dd
        = @user.position == "" ? "не указана" : @user.position
      dt
        | Бизнес достижения
      dd
        = @user.business_achievements == "" ? "пусто" : @user.business_achievements
- if current_user.id == @user.id
  .edit-user-plz
    .row
      = link_to edit_user_path(@user), class: 'btn btn-primary' do 
        span.glyphicon.glyphicon-pencil
        |  Редактировать
    .row
      = link_to new_article_path,  class: 'btn btn-primary' do 
        span.glyphicon
        |  Добавить новость
    .row
      = link_to articles_path(my_article: true),  class: 'btn btn-primary' do
        span.glyphicon
        |  Просмотр предложенных новостей 